[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "iiserpune-login-daemon"
version = "1"
dependencies = ["selenium", "keyring", "pygobject", "pydbus"]

[project.scripts]
iiserpune-login-daemon = "main:main"
